from __future__ import annotations

import sqlite3
from datetime import datetime, timedelta
import os
from pathlib import Path
import re
from typing import Any

import pandas as pd

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # PostgreSQL is optional for local SQLite development.
    psycopg = None
    dict_row = None


class DatabaseConnection:
    def __init__(self, raw_conn: Any, dialect: str):
        self.raw_conn = raw_conn
        self.dialect = dialect

    def execute(self, sql: str, params: list[Any] | tuple[Any, ...] | None = None):
        return self.raw_conn.execute(_prepare_sql(self, sql), params or [])

    def executescript(self, sql: str) -> None:
        if self.dialect == "sqlite":
            self.raw_conn.executescript(sql)
            return
        _execute_script(self, sql)

    def commit(self) -> None:
        self.raw_conn.commit()

    def rollback(self) -> None:
        self.raw_conn.rollback()

    def close(self) -> None:
        self.raw_conn.close()


_INTEGRITY_ERRORS: tuple[type[BaseException], ...] = (sqlite3.IntegrityError,)
if psycopg is not None:
    _INTEGRITY_ERRORS = (*_INTEGRITY_ERRORS, psycopg.IntegrityError)


def _prepare_sql(conn: DatabaseConnection, sql: str) -> str:
    if conn.dialect == "postgres":
        sql = sql.replace("?", "%s")
        return re.sub(r"CURRENT_TIMESTAMP(?!::text)", "(CURRENT_TIMESTAMP::text)", sql)
    return sql


def _execute_script(conn: DatabaseConnection, sql: str) -> None:
    for statement in sql.split(";"):
        statement = statement.strip()
        if statement:
            conn.execute(statement)


def _postgres_schema(sqlite_schema: str) -> str:
    return (
        sqlite_schema
        .replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        .replace("TEXT DEFAULT CURRENT_TIMESTAMP", "TEXT DEFAULT (CURRENT_TIMESTAMP::text)")
        .replace("REAL", "DOUBLE PRECISION")
    )


def db_backend(conn: DatabaseConnection) -> str:
    return conn.dialect


def connect(path: Path | str, database_url: str | None = None) -> DatabaseConnection:
    database_url = database_url or os.environ.get("DATABASE_URL")
    if database_url:
        if psycopg is None or dict_row is None:
            raise RuntimeError("DATABASE_URL foi configurado, mas o driver PostgreSQL psycopg não está instalado.")
        pg_conn = psycopg.connect(database_url, row_factory=dict_row)
        return DatabaseConnection(pg_conn, "postgres")

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return DatabaseConnection(conn, "sqlite")


def _has_column(conn: DatabaseConnection, table: str, column: str) -> bool:
    if db_backend(conn) == "sqlite":
        rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
        return any(r["name"] == column for r in rows)
    row = conn.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ?
          AND column_name = ?
        LIMIT 1
        """,
        [table, column],
    ).fetchone()
    return row is not None


def _add_column(conn: DatabaseConnection, table: str, column: str, definition: str) -> None:
    if not _has_column(conn, table, column):
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def init_db(conn: DatabaseConnection) -> None:
    schema_sql = """
        CREATE TABLE IF NOT EXISTS equipment (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            equipment_code TEXT NOT NULL UNIQUE,
            equipment_name TEXT NOT NULL,
            lab_unit TEXT,
            location TEXT,
            requires_operator INTEGER DEFAULT 0,
            responsible_name TEXT,
            responsible_phone TEXT,
            active INTEGER DEFAULT 1,
            operational_status TEXT DEFAULT 'available',
            unavailable_functions TEXT,
            max_sample_capacity INTEGER,
            capacity_unit TEXT DEFAULT 'amostras',
            capacity_enforced INTEGER DEFAULT 0,
            technical_manager TEXT,
            pop_title TEXT,
            pop_path TEXT,
            pop_version TEXT,
            pop_updated_at TEXT,
            pop_responsible TEXT,
            document_notes TEXT,
            notes TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            full_name TEXT NOT NULL,
            email TEXT,
            phone_e164 TEXT,
            role TEXT DEFAULT 'member',
            lab_unit TEXT,
            department TEXT,
            advisor_name TEXT,
            training_completed INTEGER DEFAULT 0,
            active INTEGER DEFAULT 1,
            notes TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_code TEXT,
            project_name TEXT NOT NULL,
            funding_source TEXT,
            start_date TEXT,
            end_date TEXT,
            active INTEGER DEFAULT 1,
            notes TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS bookings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            equipment_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            project_id INTEGER,
            operator_id INTEGER,
            performed_by_id INTEGER,
            start_datetime TEXT NOT NULL,
            end_datetime TEXT NOT NULL,
            sample_count INTEGER,
            purpose TEXT,
            status TEXT DEFAULT 'scheduled',
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(equipment_id) REFERENCES equipment(id),
            FOREIGN KEY(user_id) REFERENCES users(id),
            FOREIGN KEY(project_id) REFERENCES projects(id),
            FOREIGN KEY(operator_id) REFERENCES users(id),
            FOREIGN KEY(performed_by_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS maintenance_preventive (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            equipment_id INTEGER NOT NULL,
            activity_type TEXT,
            description TEXT NOT NULL,
            periodicity TEXT,
            planned_date TEXT,
            planned_end_date TEXT,
            performed_date TEXT,
            execution_time TEXT,
            checklist_path TEXT,
            internal_responsible TEXT,
            external_supplier TEXT,
            supplier_contact TEXT,
            service_order TEXT,
            status TEXT,
            certificate_path TEXT,
            observations TEXT,
            next_date TEXT,
            blocks_booking INTEGER DEFAULT 1,
            notify_internal INTEGER DEFAULT 1,
            notify_manager INTEGER DEFAULT 1,
            notify_supplier INTEGER DEFAULT 0,
            notify_users INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(equipment_id) REFERENCES equipment(id)
        );

        CREATE TABLE IF NOT EXISTS maintenance_corrective (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            equipment_id INTEGER NOT NULL,
            reporter_id INTEGER,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            occurrence_datetime TEXT,
            impact TEXT,
            priority TEXT,
            attachment_path TEXT,
            assigned_to TEXT,
            initial_diagnosis TEXT,
            probable_cause TEXT,
            operator_trained TEXT,
            external_supplier_needed INTEGER DEFAULT 0,
            corrective_action TEXT,
            replaced_parts TEXT,
            costs REAL,
            downtime_hours REAL,
            conclusion_date TEXT,
            status TEXT,
            notify_technical INTEGER DEFAULT 1,
            notify_manager INTEGER DEFAULT 1,
            notify_supplier INTEGER DEFAULT 0,
            notify_reporter INTEGER DEFAULT 1,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(equipment_id) REFERENCES equipment(id),
            FOREIGN KEY(reporter_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS supplies (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            supply_type TEXT DEFAULT 'Insumo',
            supply_name TEXT NOT NULL,
            supply_code TEXT,
            commercial_name TEXT,
            manufacturer TEXT,
            manufacturer_code TEXT,
            category TEXT,
            physical_state TEXT,
            application_function TEXT,
            addition_mode TEXT,
            compatible_model_family TEXT,
            unit TEXT DEFAULT 'kg',
            current_quantity REAL DEFAULT 0,
            minimum_quantity REAL DEFAULT 0,
            lot TEXT,
            expiration_date TEXT,
            location TEXT,
            responsible_name TEXT,
            safety_doc_path TEXT,
            technical_doc_path TEXT,
            density REAL,
            recommended_concentration TEXT,
            recommended_temperature TEXT,
            characterization_summary TEXT,
            active INTEGER DEFAULT 1,
            notes TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS supply_movements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            supply_id INTEGER NOT NULL,
            movement_type TEXT NOT NULL,
            movement_date TEXT NOT NULL,
            quantity REAL NOT NULL,
            unit TEXT,
            user_id INTEGER,
            project_id INTEGER,
            purpose TEXT,
            document_path TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(supply_id) REFERENCES supplies(id),
            FOREIGN KEY(user_id) REFERENCES users(id),
            FOREIGN KEY(project_id) REFERENCES projects(id)
        );

        CREATE TABLE IF NOT EXISTS equipment_spare_parts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            equipment_id INTEGER NOT NULL,
            supply_id INTEGER NOT NULL,
            notes TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(equipment_id) REFERENCES equipment(id),
            FOREIGN KEY(supply_id) REFERENCES supplies(id),
            UNIQUE(equipment_id, supply_id)
        );

        CREATE INDEX IF NOT EXISTS idx_equipment_spare_parts_equipment
            ON equipment_spare_parts (equipment_id, is_active);

        CREATE INDEX IF NOT EXISTS idx_equipment_spare_parts_supply
            ON equipment_spare_parts (supply_id, is_active);

        CREATE TABLE IF NOT EXISTS attachments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            entity_type TEXT NOT NULL,
            entity_id INTEGER NOT NULL,
            attachment_role TEXT NOT NULL DEFAULT 'general',
            original_filename TEXT NOT NULL,
            storage_key TEXT NOT NULL,
            storage_backend TEXT NOT NULL,
            mime_type TEXT,
            file_size INTEGER,
            sha256 TEXT,
            uploaded_by_id INTEGER,
            uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP,
            notes TEXT,
            is_active INTEGER DEFAULT 1,
            FOREIGN KEY(uploaded_by_id) REFERENCES users(id),
            UNIQUE(storage_backend, storage_key)
        );

        CREATE INDEX IF NOT EXISTS idx_attachments_entity
            ON attachments (entity_type, entity_id, is_active);

        CREATE INDEX IF NOT EXISTS idx_attachments_sha256
            ON attachments (sha256);

        CREATE TABLE IF NOT EXISTS access_codes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            email TEXT NOT NULL,
            code_hash TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            used_at TEXT,
            attempts INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS notification_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event_type TEXT NOT NULL,
            recipient_email TEXT,
            subject TEXT,
            body TEXT,
            status TEXT,
            error_message TEXT,
            related_table TEXT,
            related_id INTEGER,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        );
        """
    if db_backend(conn) == "postgres":
        _execute_script(conn, _postgres_schema(schema_sql))
    else:
        conn.executescript(schema_sql)

    # Migrações leves para bancos já criados por versões anteriores.
    _add_column(conn, "equipment", "operational_status", "TEXT DEFAULT 'available'")
    _add_column(conn, "equipment", "unavailable_functions", "TEXT")
    _add_column(conn, "equipment", "max_sample_capacity", "INTEGER")
    _add_column(conn, "equipment", "capacity_unit", "TEXT DEFAULT 'amostras'")
    _add_column(conn, "equipment", "capacity_enforced", "INTEGER DEFAULT 0")
    _add_column(conn, "equipment", "technical_manager", "TEXT")
    _add_column(conn, "equipment", "pop_title", "TEXT")
    _add_column(conn, "equipment", "pop_path", "TEXT")
    _add_column(conn, "equipment", "pop_version", "TEXT")
    _add_column(conn, "equipment", "pop_updated_at", "TEXT")
    _add_column(conn, "equipment", "pop_responsible", "TEXT")
    _add_column(conn, "equipment", "document_notes", "TEXT")
    _add_column(conn, "equipment", "updated_at", "TEXT")
    _add_column(conn, "users", "updated_at", "TEXT")
    _add_column(conn, "projects", "start_date", "TEXT")
    _add_column(conn, "projects", "end_date", "TEXT")
    _add_column(conn, "projects", "notes", "TEXT")
    _add_column(conn, "projects", "updated_at", "TEXT")
    _add_column(conn, "bookings", "performed_by_id", "INTEGER")
    _add_column(conn, "maintenance_preventive", "planned_end_date", "TEXT")
    _add_column(conn, "maintenance_preventive", "blocks_booking", "INTEGER DEFAULT 1")
    _add_column(conn, "maintenance_preventive", "updated_at", "TEXT")
    _add_column(conn, "maintenance_corrective", "updated_at", "TEXT")
    _add_column(conn, "supplies", "supply_type", "TEXT DEFAULT 'Insumo'")
    _add_column(conn, "supplies", "supply_code", "TEXT")
    _add_column(conn, "supplies", "manufacturer_code", "TEXT")
    _add_column(conn, "supplies", "compatible_model_family", "TEXT")
    conn.execute("UPDATE supplies SET supply_type = 'Insumo' WHERE supply_type IS NULL OR TRIM(supply_type) = ''")
    conn.execute("UPDATE users SET role = 'manager' WHERE LOWER(COALESCE(role, '')) IN ('operator', 'operador', 'gerente')")
    conn.commit()


def _row_to_dict(row: Any) -> dict[str, Any]:
    if isinstance(row, dict):
        return dict(row)
    return dict(row)


def query_df(conn: DatabaseConnection, sql: str, params: list[Any] | tuple[Any, ...] | None = None) -> pd.DataFrame:
    cur = conn.execute(sql, params or [])
    columns = [col[0] for col in cur.description or []]
    rows = cur.fetchall()
    if not rows:
        return pd.DataFrame(columns=columns)
    return pd.DataFrame([_row_to_dict(row) for row in rows], columns=columns)


OPERATIONAL_TABLES = [
    "equipment",
    "users",
    "projects",
    "bookings",
    "maintenance_preventive",
    "maintenance_corrective",
    "supplies",
    "supply_movements",
    "equipment_spare_parts",
]


ALL_TABLES = [
    *OPERATIONAL_TABLES,
    "attachments",
    "access_codes",
    "notification_log",
]


def table_counts(conn: DatabaseConnection) -> dict[str, int]:
    counts: dict[str, int] = {}
    for table in ALL_TABLES:
        counts[table] = conn.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()["n"]
    return counts


def is_operational_database_empty(conn: DatabaseConnection) -> bool:
    counts = table_counts(conn)
    return all(counts.get(table, 0) == 0 for table in OPERATIONAL_TABLES)


def insert_returning_id(
    conn: DatabaseConnection,
    sql: str,
    params: list[Any] | tuple[Any, ...],
) -> int:
    new_id = _execute_insert_returning_id(conn, sql, params)
    conn.commit()
    return new_id


def _execute_insert_returning_id(
    conn: DatabaseConnection,
    sql: str,
    params: list[Any] | tuple[Any, ...],
) -> int:
    if db_backend(conn) == "postgres":
        row = conn.execute(f"{sql.rstrip().rstrip(';')} RETURNING id", params).fetchone()
        return int(row["id"])
    cur = conn.execute(sql, params)
    return int(cur.lastrowid)


def link_spare_part_to_equipment(
    conn: DatabaseConnection,
    *,
    equipment_id: int,
    supply_id: int,
    notes: str | None = None,
) -> int:
    existing = conn.execute(
        """
        SELECT id
        FROM equipment_spare_parts
        WHERE equipment_id = ? AND supply_id = ?
        """,
        [equipment_id, supply_id],
    ).fetchone()
    if existing:
        conn.execute(
            """
            UPDATE equipment_spare_parts
            SET is_active = 1,
                notes = COALESCE(?, notes),
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            [notes, existing["id"]],
        )
        conn.commit()
        return int(existing["id"])

    return insert_returning_id(
        conn,
        """
        INSERT INTO equipment_spare_parts (
            equipment_id, supply_id, notes, is_active
        )
        VALUES (?, ?, ?, 1)
        """,
        [equipment_id, supply_id, notes],
    )


def unlink_spare_part_from_equipment(
    conn: DatabaseConnection,
    *,
    equipment_id: int,
    supply_id: int,
) -> None:
    conn.execute(
        """
        UPDATE equipment_spare_parts
        SET is_active = 0,
            updated_at = CURRENT_TIMESTAMP
        WHERE equipment_id = ? AND supply_id = ? AND is_active = 1
        """,
        [equipment_id, supply_id],
    )
    conn.commit()


def set_spare_part_equipment_links(
    conn: DatabaseConnection,
    *,
    supply_id: int,
    equipment_ids: list[int] | tuple[int, ...],
) -> None:
    target_ids = sorted({int(equipment_id) for equipment_id in equipment_ids})
    for equipment_id in target_ids:
        link_spare_part_to_equipment(conn, equipment_id=equipment_id, supply_id=supply_id)

    if target_ids:
        placeholders = ", ".join(["?"] * len(target_ids))
        conn.execute(
            f"""
            UPDATE equipment_spare_parts
            SET is_active = 0,
                updated_at = CURRENT_TIMESTAMP
            WHERE supply_id = ?
              AND is_active = 1
              AND equipment_id NOT IN ({placeholders})
            """,
            [supply_id, *target_ids],
        )
    else:
        conn.execute(
            """
            UPDATE equipment_spare_parts
            SET is_active = 0,
                updated_at = CURRENT_TIMESTAMP
            WHERE supply_id = ? AND is_active = 1
            """,
            [supply_id],
        )
    conn.commit()


def list_spare_parts_for_equipment(
    conn: DatabaseConnection,
    equipment_id: int,
    *,
    include_inactive: bool = False,
) -> pd.DataFrame:
    sql = """
        SELECT esp.id AS association_id,
               esp.notes AS association_notes,
               esp.is_active AS association_active,
               esp.created_at AS association_created_at,
               esp.updated_at AS association_updated_at,
               s.*
        FROM equipment_spare_parts esp
        JOIN supplies s ON s.id = esp.supply_id
        WHERE esp.equipment_id = ?
          AND COALESCE(s.supply_type, 'Insumo') = 'Peça de reposição'
    """
    params: list[Any] = [equipment_id]
    if not include_inactive:
        sql += " AND esp.is_active = 1 AND s.active = 1"
    sql += " ORDER BY s.supply_name"
    return query_df(conn, sql, params)


def list_equipment_for_spare_part(
    conn: DatabaseConnection,
    supply_id: int,
    *,
    include_inactive: bool = False,
) -> pd.DataFrame:
    sql = """
        SELECT esp.id AS association_id,
               esp.notes AS association_notes,
               esp.is_active AS association_active,
               esp.created_at AS association_created_at,
               esp.updated_at AS association_updated_at,
               e.*
        FROM equipment_spare_parts esp
        JOIN equipment e ON e.id = esp.equipment_id
        WHERE esp.supply_id = ?
    """
    params: list[Any] = [supply_id]
    if not include_inactive:
        sql += " AND esp.is_active = 1"
    sql += " ORDER BY e.active DESC, e.equipment_code"
    return query_df(conn, sql, params)


def list_spare_part_options(conn: DatabaseConnection, *, active_only: bool = True) -> pd.DataFrame:
    sql = """
        SELECT *
        FROM supplies
        WHERE COALESCE(supply_type, 'Insumo') = 'Peça de reposição'
    """
    params: list[Any] = []
    if active_only:
        sql += " AND active = 1"
    sql += " ORDER BY supply_name"
    return query_df(conn, sql, params)


def create_attachment(
    conn: DatabaseConnection,
    *,
    entity_type: str,
    entity_id: int,
    attachment_role: str,
    original_filename: str,
    storage_key: str,
    storage_backend: str,
    mime_type: str | None,
    file_size: int,
    sha256: str,
    uploaded_by_id: int | None,
    notes: str | None = None,
    is_active: int = 1,
) -> int:
    return insert_returning_id(
        conn,
        """
        INSERT INTO attachments (
            entity_type, entity_id, attachment_role, original_filename,
            storage_key, storage_backend, mime_type, file_size, sha256,
            uploaded_by_id, notes, is_active
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            entity_type,
            entity_id,
            attachment_role,
            original_filename,
            storage_key,
            storage_backend,
            mime_type,
            file_size,
            sha256,
            uploaded_by_id,
            notes,
            is_active,
        ],
    )


def list_attachments(
    conn: DatabaseConnection,
    *,
    entity_type: str,
    entity_id: int,
    attachment_role: str | None = None,
    active_only: bool = True,
) -> list[Any]:
    sql = """
        SELECT *
        FROM attachments
        WHERE entity_type = ?
          AND entity_id = ?
    """
    params: list[Any] = [entity_type, entity_id]
    if attachment_role:
        sql += " AND attachment_role = ?"
        params.append(attachment_role)
    if active_only:
        sql += " AND COALESCE(is_active, 1) = 1"
    sql += " ORDER BY uploaded_at DESC, id DESC"
    return conn.execute(sql, params).fetchall()


def get_attachment(conn: DatabaseConnection, attachment_id: int) -> Any | None:
    return conn.execute("SELECT * FROM attachments WHERE id = ?", [attachment_id]).fetchone()


def get_latest_attachment_for_entity(
    conn: DatabaseConnection,
    *,
    entity_type: str,
    entity_id: int,
    attachment_role: str | None = None,
) -> Any | None:
    rows = list_attachments(
        conn,
        entity_type=entity_type,
        entity_id=entity_id,
        attachment_role=attachment_role,
        active_only=True,
    )
    return rows[0] if rows else None


def deactivate_attachment(conn: DatabaseConnection, attachment_id: int) -> None:
    conn.execute("UPDATE attachments SET is_active = 0 WHERE id = ?", [attachment_id])
    conn.commit()


_LEGACY_ATTACHMENT_COLUMNS: dict[str, set[str]] = {
    "supplies": {"safety_doc_path", "technical_doc_path"},
    "supply_movements": {"document_path"},
    "maintenance_preventive": {"checklist_path", "certificate_path"},
    "maintenance_corrective": {"attachment_path"},
}


def update_legacy_attachment_path(
    conn: DatabaseConnection,
    *,
    table: str,
    row_id: int,
    column: str,
    value: str | None,
) -> None:
    if column not in _LEGACY_ATTACHMENT_COLUMNS.get(table, set()):
        raise ValueError("Campo legado de anexo não permitido.")
    updated_at = ", updated_at = CURRENT_TIMESTAMP" if table != "supply_movements" else ""
    conn.execute(f"UPDATE {table} SET {column} = ?{updated_at} WHERE id = ?", [value, row_id])
    conn.commit()


def get_active_user_by_email(conn: sqlite3.Connection, email: str) -> sqlite3.Row | None:
    email = str(email or "").strip().lower()
    if not email:
        return None
    return conn.execute(
        """
        SELECT *
        FROM users
        WHERE active = 1
          AND email IS NOT NULL
          AND LOWER(TRIM(email)) = ?
        LIMIT 1
        """,
        [email],
    ).fetchone()


def create_access_code_record(
    conn: sqlite3.Connection,
    *,
    user_id: int,
    email: str,
    code_hash: str,
    expires_at: str,
) -> None:
    conn.execute(
        "UPDATE access_codes SET used_at = CURRENT_TIMESTAMP WHERE user_id = ? AND used_at IS NULL",
        [user_id],
    )
    conn.execute(
        """
        INSERT INTO access_codes (user_id, email, code_hash, expires_at)
        VALUES (?, ?, ?, ?)
        """,
        [user_id, email, code_hash, expires_at],
    )
    conn.commit()


def verify_access_code_record(conn: sqlite3.Connection, *, email: str, code_hash: str) -> tuple[bool, str, sqlite3.Row | None]:
    email = str(email or "").strip().lower()
    if not email:
        return False, "E-mail não informado. Solicite uma nova senha volátil.", None
    if not code_hash:
        return False, "Código não informado.", None
    row = conn.execute(
        """
        SELECT ac.*, u.full_name, u.role, u.active, u.email AS user_email
        FROM access_codes ac
        JOIN users u ON u.id = ac.user_id
        WHERE LOWER(TRIM(ac.email)) = ?
          AND ac.used_at IS NULL
          AND ac.code_hash = ?
        ORDER BY ac.created_at DESC, ac.id DESC
        LIMIT 1
        """,
        [email, code_hash],
    ).fetchone()
    if not row:
        active_for_email = conn.execute(
            """
            SELECT id
            FROM access_codes
            WHERE LOWER(TRIM(email)) = ?
              AND used_at IS NULL
            ORDER BY created_at DESC, id DESC
            LIMIT 1
            """,
            [email],
        ).fetchone()
        if active_for_email:
            conn.execute(
                "UPDATE access_codes SET attempts = COALESCE(attempts, 0) + 1 WHERE id = ?",
                [active_for_email["id"]],
            )
            conn.commit()
            return False, "Código inválido. Use o código mais recente recebido por e-mail.", None
        return False, "Nenhum código ativo encontrado para este e-mail. Solicite uma nova senha volátil.", None
    if int(row["active"] or 0) != 1:
        return False, "Usuário inativo.", None
    try:
        expired = datetime.fromisoformat(str(row["expires_at"])) < datetime.now()
    except Exception:
        expired = True
    if expired:
        conn.execute("UPDATE access_codes SET used_at = CURRENT_TIMESTAMP WHERE id = ?", [row["id"]])
        conn.commit()
        return False, "Código expirado. Solicite um novo código.", None
    if int(row["attempts"] or 0) >= 5:
        conn.execute("UPDATE access_codes SET used_at = CURRENT_TIMESTAMP WHERE id = ?", [row["id"]])
        conn.commit()
        return False, "Muitas tentativas. Solicite um novo código.", None
    conn.execute("UPDATE access_codes SET used_at = CURRENT_TIMESTAMP WHERE id = ?", [row["id"]])
    conn.commit()
    return True, "Acesso liberado.", row


def log_notification(
    conn: sqlite3.Connection,
    *,
    event_type: str,
    recipient_email: str | None,
    subject: str,
    body: str,
    status: str,
    error_message: str | None = None,
    related_table: str | None = None,
    related_id: int | None = None,
) -> None:
    conn.execute(
        """
        INSERT INTO notification_log (
            event_type, recipient_email, subject, body, status,
            error_message, related_table, related_id
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [event_type, recipient_email, subject, body, status, error_message, related_table, related_id],
    )
    conn.commit()


def _norm_col(name: str) -> str:
    return (
        str(name)
        .strip()
        .lower()
        .replace("á", "a")
        .replace("à", "a")
        .replace("ã", "a")
        .replace("â", "a")
        .replace("é", "e")
        .replace("ê", "e")
        .replace("í", "i")
        .replace("ó", "o")
        .replace("õ", "o")
        .replace("ô", "o")
        .replace("ú", "u")
        .replace("ç", "c")
        .replace("/", "_")
        .replace("-", "_")
        .replace(" ", "_")
    )


def _first(row: pd.Series, *names: str, default: Any = None) -> Any:
    normalized = {_norm_col(c): c for c in row.index}
    for name in names:
        key = _norm_col(name)
        if key in normalized:
            value = row[normalized[key]]
            if pd.notna(value):
                return value
    for name in names:
        key = _norm_col(name)
        for normalized_col, original_col in normalized.items():
            if key and key in normalized_col:
                value = row[original_col]
                if pd.notna(value):
                    return value
    return default


def _to_bool_int(value: Any, default: int = 0) -> int:
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except Exception:
        pass
    if isinstance(value, bool):
        return int(value)
    text = str(value).strip().lower()
    if text in {"1", "true", "sim", "yes", "y", "ativo", "concluído", "concluido"}:
        return 1
    if text in {"0", "false", "não", "nao", "no", "n", "inativo"}:
        return 0
    return default


def _clean_excel_value(value: Any) -> Any:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except Exception:
        pass
    if isinstance(value, pd.Timestamp):
        return value.date().isoformat()
    if isinstance(value, float) and value.is_integer():
        text = str(int(value))
    else:
        text = str(value).strip()
    if text.lower() in {"", "nan", "none", "nat"}:
        return None
    return text


def _normalize_role(value: Any) -> str:
    role = str(_clean_excel_value(value) or "member").strip().lower()
    aliases = {
        "administrador": "admin",
        "admin": "admin",
        "gerente": "manager",
        "manager": "manager",
        "operator": "manager",
        "operador": "manager",
        "membro": "member",
        "member": "member",
        "usuario": "member",
        "usuário": "member",
        "user": "member",
    }
    return aliases.get(role, "member")


def import_base_xlsx(conn: sqlite3.Connection, path: Path | str) -> dict[str, int]:
    """Importa uma base Excel simples, aceitando nomes de abas flexíveis."""
    path = Path(path)
    xl = pd.ExcelFile(path)
    counts = {"equipment": 0, "users": 0, "projects": 0}

    for sheet in xl.sheet_names:
        df = pd.read_excel(path, sheet_name=sheet)
        if df.empty:
            continue
        sheet_key = _norm_col(sheet)

        if "equip" in sheet_key:
            for _, row in df.iterrows():
                code = str(_first(row, "equipment_code", "codigo", "código", "patrimonio", "patrimônio", default="")).strip()
                name = str(_first(row, "equipment_name", "equipamento", "nome", default="")).strip()
                if not code or not name:
                    continue
                conn.execute(
                    """
                    INSERT INTO equipment (
                        equipment_code, equipment_name, lab_unit, location, requires_operator,
                        responsible_name, responsible_phone, active, operational_status,
                        unavailable_functions, max_sample_capacity, capacity_unit,
                        capacity_enforced, technical_manager, pop_title, pop_path,
                        pop_version, pop_updated_at, pop_responsible, document_notes, notes
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(equipment_code) DO UPDATE SET
                        equipment_name=excluded.equipment_name,
                        lab_unit=excluded.lab_unit,
                        location=excluded.location,
                        requires_operator=excluded.requires_operator,
                        responsible_name=excluded.responsible_name,
                        responsible_phone=excluded.responsible_phone,
                        active=excluded.active,
                        operational_status=excluded.operational_status,
                        unavailable_functions=excluded.unavailable_functions,
                        max_sample_capacity=excluded.max_sample_capacity,
                        capacity_unit=excluded.capacity_unit,
                        capacity_enforced=excluded.capacity_enforced,
                        technical_manager=excluded.technical_manager,
                        pop_title=excluded.pop_title,
                        pop_path=excluded.pop_path,
                        pop_version=excluded.pop_version,
                        pop_updated_at=excluded.pop_updated_at,
                        pop_responsible=excluded.pop_responsible,
                        document_notes=excluded.document_notes,
                        notes=excluded.notes,
                        updated_at=CURRENT_TIMESTAMP
                    """,
                    (
                        code,
                        name,
                        _clean_excel_value(_first(row, "lab_unit", "unidade")),
                        _clean_excel_value(_first(row, "location", "local", "localizacao", "localização")),
                        _to_bool_int(_first(row, "requires_operator", "requer_operador", "operador", default=0)),
                        _clean_excel_value(_first(row, "responsible_name", "responsavel", "responsável")),
                        _clean_excel_value(_first(row, "responsible_phone", "telefone")),
                        _to_bool_int(_first(row, "active", "ativo", default=1), default=1),
                        _clean_excel_value(_first(row, "operational_status", "status_operacional", default="available")) or "available",
                        _clean_excel_value(_first(row, "unavailable_functions", "funcionalidades_indisponiveis", "funcionalidades_indisponíveis")),
                        _clean_excel_value(_first(row, "max_sample_capacity", "capacidade_maxima", "capacidade_máxima")),
                        _clean_excel_value(_first(row, "capacity_unit", "unidade_da_capacidade")),
                        _to_bool_int(_first(row, "capacity_enforced", "bloqueia_acima_da_capacidade", default=0)),
                        _clean_excel_value(_first(row, "technical_manager", "gestor_tecnico", "gestor_técnico")),
                        _clean_excel_value(_first(row, "pop_title", "titulo_pop", "título_pop")),
                        _clean_excel_value(_first(row, "pop_path", "caminho_pop", "link_pop")),
                        _clean_excel_value(_first(row, "pop_version", "versao_pop", "versão_pop")),
                        _clean_excel_value(_first(row, "pop_updated_at", "data_pop", "atualizacao_pop", "atualização_pop")),
                        _clean_excel_value(_first(row, "pop_responsible", "responsavel_pop", "responsável_pop")),
                        _clean_excel_value(_first(row, "document_notes", "observacoes_documentais", "observações_documentais")),
                        _clean_excel_value(_first(row, "notes", "observacoes", "observações")),
                    ),
                )
                counts["equipment"] += 1

        elif "usuario" in sheet_key or "user" in sheet_key:
            for _, row in df.iterrows():
                name = str(_first(row, "full_name", "nome", "nome_completo", default="")).strip()
                if not name:
                    continue
                email = _clean_excel_value(_first(row, "email", "e-mail"))
                phone = _clean_excel_value(_first(row, "phone_e164", "telefone", "celular"))
                existing = None
                if email:
                    existing = conn.execute("SELECT id FROM users WHERE LOWER(COALESCE(email, '')) = LOWER(?) LIMIT 1", [email]).fetchone()
                if existing is None and phone:
                    existing = conn.execute("SELECT id FROM users WHERE COALESCE(phone_e164, '') = ? LIMIT 1", [phone]).fetchone()
                if existing is None:
                    existing = conn.execute("SELECT id FROM users WHERE LOWER(full_name) = LOWER(?) LIMIT 1", [name]).fetchone()
                values = (
                    name,
                    email,
                    phone,
                    _normalize_role(_first(row, "role", "perfil", default="member")),
                    _clean_excel_value(_first(row, "lab_unit", "unidade")),
                    _clean_excel_value(_first(row, "department", "departamento", "programa")),
                    _clean_excel_value(_first(row, "advisor_name", "orientador")),
                    _to_bool_int(_first(row, "training_completed", "treinamento", default=0)),
                    _to_bool_int(_first(row, "active", "ativo", default=1), default=1),
                    _clean_excel_value(_first(row, "notes", "observacoes", "observações")),
                )
                if existing:
                    conn.execute(
                        """
                        UPDATE users
                        SET full_name = ?,
                            email = ?,
                            phone_e164 = ?,
                            role = ?,
                            lab_unit = ?,
                            department = ?,
                            advisor_name = ?,
                            training_completed = ?,
                            active = ?,
                            notes = ?,
                            updated_at = CURRENT_TIMESTAMP
                        WHERE id = ?
                        """,
                        (*values, int(existing["id"])),
                    )
                else:
                    conn.execute(
                        """
                        INSERT INTO users (full_name, email, phone_e164, role, lab_unit, department, advisor_name, training_completed, active, notes)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        values,
                    )
                counts["users"] += 1

        elif "projeto" in sheet_key or "project" in sheet_key:
            for _, row in df.iterrows():
                name = str(_first(row, "project_name", "projeto", "nome", default="")).strip()
                if not name:
                    continue
                project_code = _clean_excel_value(_first(row, "project_code", "codigo", "código"))
                existing = None
                if project_code:
                    existing = conn.execute("SELECT id FROM projects WHERE LOWER(COALESCE(project_code, '')) = LOWER(?) LIMIT 1", [project_code]).fetchone()
                if existing is None:
                    existing = conn.execute("SELECT id FROM projects WHERE LOWER(project_name) = LOWER(?) LIMIT 1", [name]).fetchone()
                values = (
                    project_code,
                    name,
                    _clean_excel_value(_first(row, "funding_source", "financiador", "fonte")),
                    _clean_excel_value(_first(row, "start_date", "data_inicio", "data_de_inicio", "início", "inicio")),
                    _clean_excel_value(_first(row, "end_date", "data_fim", "data_de_fim", "fim", "termino", "término")),
                    _to_bool_int(_first(row, "active", "ativo", default=1), default=1),
                    _clean_excel_value(_first(row, "notes", "observacoes", "observações")),
                )
                if existing:
                    conn.execute(
                        """
                        UPDATE projects
                        SET project_code = ?,
                            project_name = ?,
                            funding_source = ?,
                            start_date = ?,
                            end_date = ?,
                            active = ?,
                            notes = ?,
                            updated_at = CURRENT_TIMESTAMP
                        WHERE id = ?
                        """,
                        (*values, int(existing["id"])),
                    )
                else:
                    conn.execute(
                        """
                        INSERT INTO projects (project_code, project_name, funding_source, start_date, end_date, active, notes)
                        VALUES (?, ?, ?, ?, ?, ?, ?)
                        """,
                        values,
                    )
                counts["projects"] += 1

    conn.commit()
    return counts


def seed_default_pops(conn: sqlite3.Connection) -> int:
    """Associa POPs locais às famílias de equipamentos já cadastradas."""
    mappings = [
        ("AUT", "POP - Autoclave", "assets/pops/POP_Autoclave.pdf"),
        ("UCA", "POP - Ultrasonic Cement Analyzer (UCA)", "assets/pops/POP_UCA.pdf"),
        ("CP", "POP - Consistômetro pressurizado", "assets/pops/POP_Consistometro_pressurizado.pdf"),
        ("FP", "POP - Filtro prensa", "assets/pops/POP_Filtro.pdf"),
        ("REO", "POP - Reômetro", "assets/pops/POP_Reometro.pdf"),
    ]
    updated = 0
    for prefix, title, path in mappings:
        cur = conn.execute(
            """
            UPDATE equipment
            SET pop_title = COALESCE(NULLIF(pop_title, ''), ?),
                pop_path = COALESCE(NULLIF(pop_path, ''), ?),
                pop_version = COALESCE(NULLIF(pop_version, ''), 'v1'),
                pop_responsible = COALESCE(NULLIF(pop_responsible, ''), technical_manager, responsible_name),
                document_notes = COALESCE(NULLIF(document_notes, ''), 'POP local incluído na versão v7.4 do LabCim Manager.'),
                updated_at = CURRENT_TIMESTAMP
            WHERE equipment_code LIKE ?
              AND (pop_path IS NULL OR TRIM(pop_path) = '')
            """,
            [title, path, f"{prefix}%"],
        )
        updated += cur.rowcount if cur.rowcount is not None else 0
    conn.commit()
    return updated


def _overlap_clause(start_iso: str, end_iso: str) -> tuple[str, list[str]]:
    return "(start_datetime < ? AND end_datetime > ?)", [end_iso, start_iso]


def _booking_conflict(conn: sqlite3.Connection, equipment_id: int, start_iso: str, end_iso: str) -> sqlite3.Row | None:
    clause, params = _overlap_clause(start_iso, end_iso)
    return conn.execute(
        f"""
        SELECT id, start_datetime, end_datetime, status
        FROM bookings
        WHERE equipment_id = ?
          AND status NOT IN ('cancelled', 'no_show')
          AND {clause}
        LIMIT 1
        """,
        [equipment_id, *params],
    ).fetchone()


def _preventive_conflict(conn: sqlite3.Connection, equipment_id: int, start_iso: str, end_iso: str) -> sqlite3.Row | None:
    start_dt = datetime.fromisoformat(start_iso)
    end_dt = datetime.fromisoformat(end_iso)
    rows = conn.execute(
        """
        SELECT id, activity_type, description, planned_date, planned_end_date, status
        FROM maintenance_preventive
        WHERE equipment_id = ?
          AND COALESCE(blocks_booking, 1) = 1
          AND LOWER(COALESCE(status, 'pendente')) NOT IN ('realizado', 'concluído', 'concluido', 'cancelado')
          AND planned_date IS NOT NULL
        """,
        [equipment_id],
    ).fetchall()
    for row in rows:
        try:
            prev_start = datetime.fromisoformat(str(row["planned_date"]))
        except ValueError:
            prev_start = datetime.fromisoformat(str(row["planned_date"]) + "T00:00:00")
        if row["planned_end_date"]:
            try:
                prev_end = datetime.fromisoformat(str(row["planned_end_date"]))
            except ValueError:
                prev_end = datetime.fromisoformat(str(row["planned_end_date"]) + "T23:59:59")
        else:
            prev_end = prev_start + timedelta(days=1)
        if prev_start < end_dt and prev_end > start_dt:
            return row
    return None


def create_booking(
    conn: sqlite3.Connection,
    *,
    equipment_id: int,
    user_id: int,
    project_id: int | None,
    operator_id: int | None,
    start_iso: str,
    end_iso: str,
    sample_count: int | None,
    purpose: str | None,
    performed_by_id: int | None = None,
) -> tuple[bool, str, int | None]:
    eq = conn.execute("SELECT * FROM equipment WHERE id = ?", [equipment_id]).fetchone()
    if not eq:
        return False, "Equipamento não encontrado.", None
    if int(eq["active"] or 0) != 1:
        return False, "Este equipamento está inativo.", None
    if eq["operational_status"] == "maintenance":
        return False, "Este equipamento está marcado como em manutenção.", None
    if sample_count and eq["max_sample_capacity"] and sample_count > int(eq["max_sample_capacity"]):
        if int(eq["capacity_enforced"] or 0) == 1:
            return False, f"A quantidade excede a capacidade máxima cadastrada ({eq['max_sample_capacity']} {eq['capacity_unit'] or 'amostras'}).", None

    conflict = _booking_conflict(conn, equipment_id, start_iso, end_iso)
    if conflict:
        return False, f"Conflito com a reserva #{conflict['id']} ({conflict['start_datetime']} a {conflict['end_datetime']}).", None

    maintenance = _preventive_conflict(conn, equipment_id, start_iso, end_iso)
    if maintenance:
        return False, f"Conflito com manutenção/calibração #{maintenance['id']}: {maintenance['description']}.", None

    booking_id = insert_returning_id(
        conn,
        """
        INSERT INTO bookings (
            equipment_id, user_id, project_id, operator_id, performed_by_id,
            start_datetime, end_datetime, sample_count, purpose, status
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'scheduled')
        """,
        [equipment_id, user_id, project_id, operator_id, performed_by_id, start_iso, end_iso, sample_count, purpose],
    )
    return True, "Reserva registrada com sucesso.", booking_id


def update_booking_status(conn: sqlite3.Connection, booking_id: int, status: str) -> None:
    conn.execute("UPDATE bookings SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?", [status, booking_id])
    conn.commit()


def update_equipment_operational_info(
    conn: sqlite3.Connection,
    equipment_id: int,
    *,
    location: str | None,
    operational_status: str,
    unavailable_functions: str | None,
    max_sample_capacity: int | None,
    capacity_unit: str | None,
    capacity_enforced: int,
    technical_manager: str | None,
    pop_title: str | None,
    pop_path: str | None,
    pop_version: str | None,
    pop_updated_at: str | None,
    pop_responsible: str | None,
    document_notes: str | None,
    notes: str | None,
) -> None:
    conn.execute(
        """
        UPDATE equipment
        SET location = ?,
            operational_status = ?,
            unavailable_functions = ?,
            max_sample_capacity = ?,
            capacity_unit = ?,
            capacity_enforced = ?,
            technical_manager = ?,
            pop_title = ?,
            pop_path = ?,
            pop_version = ?,
            pop_updated_at = ?,
            pop_responsible = ?,
            document_notes = ?,
            notes = ?,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        """,
        [
            location,
            operational_status,
            unavailable_functions,
            max_sample_capacity,
            capacity_unit,
            capacity_enforced,
            technical_manager,
            pop_title,
            pop_path,
            pop_version,
            pop_updated_at,
            pop_responsible,
            document_notes,
            notes,
            equipment_id,
        ],
    )
    conn.commit()


def create_equipment(
    conn: sqlite3.Connection,
    *,
    equipment_code: str,
    equipment_name: str,
    lab_unit: str | None,
    location: str | None,
    requires_operator: int,
    responsible_name: str | None,
    responsible_phone: str | None,
    active: int,
    operational_status: str,
    unavailable_functions: str | None,
    max_sample_capacity: int | None,
    capacity_unit: str | None,
    capacity_enforced: int,
    technical_manager: str | None,
    pop_title: str | None,
    pop_path: str | None,
    pop_version: str | None,
    pop_updated_at: str | None,
    pop_responsible: str | None,
    document_notes: str | None,
    notes: str | None,
) -> tuple[bool, str]:
    equipment_code = equipment_code.strip()
    equipment_name = equipment_name.strip()
    if not equipment_code or not equipment_name:
        return False, "Informe código e nome do equipamento."
    try:
        conn.execute(
            """
            INSERT INTO equipment (
                equipment_code, equipment_name, lab_unit, location, requires_operator,
                responsible_name, responsible_phone, active, operational_status,
                unavailable_functions, max_sample_capacity, capacity_unit,
                capacity_enforced, technical_manager, pop_title, pop_path,
                pop_version, pop_updated_at, pop_responsible, document_notes, notes
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                equipment_code,
                equipment_name,
                lab_unit,
                location,
                requires_operator,
                responsible_name,
                responsible_phone,
                active,
                operational_status,
                unavailable_functions,
                max_sample_capacity,
                capacity_unit,
                capacity_enforced,
                technical_manager,
                pop_title,
                pop_path,
                pop_version,
                pop_updated_at,
                pop_responsible,
                document_notes,
                notes,
            ],
        )
        conn.commit()
        return True, "Equipamento cadastrado com sucesso."
    except _INTEGRITY_ERRORS:
        return False, "Já existe um equipamento com este código."


def update_equipment_master(
    conn: sqlite3.Connection,
    equipment_id: int,
    *,
    equipment_code: str,
    equipment_name: str,
    lab_unit: str | None,
    location: str | None,
    requires_operator: int,
    responsible_name: str | None,
    responsible_phone: str | None,
    active: int,
    operational_status: str,
    unavailable_functions: str | None,
    max_sample_capacity: int | None,
    capacity_unit: str | None,
    capacity_enforced: int,
    technical_manager: str | None,
    pop_title: str | None,
    pop_path: str | None,
    pop_version: str | None,
    pop_updated_at: str | None,
    pop_responsible: str | None,
    document_notes: str | None,
    notes: str | None,
) -> tuple[bool, str]:
    equipment_code = equipment_code.strip()
    equipment_name = equipment_name.strip()
    if not equipment_code or not equipment_name:
        return False, "Informe código e nome do equipamento."
    try:
        conn.execute(
            """
            UPDATE equipment
            SET equipment_code = ?,
                equipment_name = ?,
                lab_unit = ?,
                location = ?,
                requires_operator = ?,
                responsible_name = ?,
                responsible_phone = ?,
                active = ?,
                operational_status = ?,
                unavailable_functions = ?,
                max_sample_capacity = ?,
                capacity_unit = ?,
                capacity_enforced = ?,
                technical_manager = ?,
                pop_title = ?,
                pop_path = ?,
                pop_version = ?,
                pop_updated_at = ?,
                pop_responsible = ?,
                document_notes = ?,
                notes = ?,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            [
                equipment_code,
                equipment_name,
                lab_unit,
                location,
                requires_operator,
                responsible_name,
                responsible_phone,
                active,
                operational_status,
                unavailable_functions,
                max_sample_capacity,
                capacity_unit,
                capacity_enforced,
                technical_manager,
                pop_title,
                pop_path,
                pop_version,
                pop_updated_at,
                pop_responsible,
                document_notes,
                notes,
                equipment_id,
            ],
        )
        conn.commit()
        return True, "Equipamento atualizado com sucesso."
    except _INTEGRITY_ERRORS:
        return False, "Já existe outro equipamento com este código."


def create_user(
    conn: sqlite3.Connection,
    *,
    full_name: str,
    email: str | None,
    phone_e164: str | None,
    role: str,
    lab_unit: str | None,
    department: str | None,
    advisor_name: str | None,
    training_completed: int,
    active: int,
    notes: str | None,
) -> tuple[bool, str]:
    full_name = full_name.strip()
    if not full_name:
        return False, "Informe o nome completo do usuário."
    role = _normalize_role(role)
    conn.execute(
        """
        INSERT INTO users (
            full_name, email, phone_e164, role, lab_unit, department,
            advisor_name, training_completed, active, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [full_name, email, phone_e164, role, lab_unit, department, advisor_name, training_completed, active, notes],
    )
    conn.commit()
    return True, "Usuário cadastrado com sucesso."


def update_user(
    conn: sqlite3.Connection,
    user_id: int,
    *,
    full_name: str,
    email: str | None,
    phone_e164: str | None,
    role: str,
    lab_unit: str | None,
    department: str | None,
    advisor_name: str | None,
    training_completed: int,
    active: int,
    notes: str | None,
) -> tuple[bool, str]:
    full_name = full_name.strip()
    if not full_name:
        return False, "Informe o nome completo do usuário."
    role = _normalize_role(role)
    conn.execute(
        """
        UPDATE users
        SET full_name = ?,
            email = ?,
            phone_e164 = ?,
            role = ?,
            lab_unit = ?,
            department = ?,
            advisor_name = ?,
            training_completed = ?,
            active = ?,
            notes = ?,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        """,
        [full_name, email, phone_e164, role, lab_unit, department, advisor_name, training_completed, active, notes, user_id],
    )
    conn.commit()
    return True, "Usuário atualizado com sucesso."


def create_project(
    conn: sqlite3.Connection,
    *,
    project_code: str | None,
    project_name: str,
    funding_source: str | None,
    start_date: str | None,
    end_date: str | None,
    active: int,
    notes: str | None,
) -> tuple[bool, str]:
    project_name = project_name.strip()
    if not project_name:
        return False, "Informe o nome do projeto."
    conn.execute(
        """
        INSERT INTO projects (
            project_code, project_name, funding_source, start_date, end_date, active, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        [project_code, project_name, funding_source, start_date, end_date, active, notes],
    )
    conn.commit()
    return True, "Projeto cadastrado com sucesso."


def update_project(
    conn: sqlite3.Connection,
    project_id: int,
    *,
    project_code: str | None,
    project_name: str,
    funding_source: str | None,
    start_date: str | None,
    end_date: str | None,
    active: int,
    notes: str | None,
) -> tuple[bool, str]:
    project_name = project_name.strip()
    if not project_name:
        return False, "Informe o nome do projeto."
    conn.execute(
        """
        UPDATE projects
        SET project_code = ?,
            project_name = ?,
            funding_source = ?,
            start_date = ?,
            end_date = ?,
            active = ?,
            notes = ?,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        """,
        [project_code, project_name, funding_source, start_date, end_date, active, notes, project_id],
    )
    conn.commit()
    return True, "Projeto atualizado com sucesso."


def create_preventive_activity(
    conn: sqlite3.Connection,
    *,
    equipment_id: int,
    activity_type: str,
    description: str,
    periodicity: str,
    planned_date: str | None,
    performed_date: str | None,
    execution_time: str | None,
    checklist_path: str | None,
    internal_responsible: str | None,
    external_supplier: str | None,
    supplier_contact: str | None,
    service_order: str | None,
    status: str,
    certificate_path: str | None,
    observations: str | None,
    next_date: str | None,
    notify_internal: int,
    notify_manager: int,
    notify_supplier: int,
    notify_users: int,
    planned_end_date: str | None = None,
    blocks_booking: int = 1,
) -> int:
    return insert_returning_id(
        conn,
        """
        INSERT INTO maintenance_preventive (
            equipment_id, activity_type, description, periodicity, planned_date, planned_end_date,
            performed_date, execution_time, checklist_path, internal_responsible,
            external_supplier, supplier_contact, service_order, status, certificate_path,
            observations, next_date, blocks_booking, notify_internal, notify_manager,
            notify_supplier, notify_users
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            equipment_id,
            activity_type,
            description,
            periodicity,
            planned_date,
            planned_end_date,
            performed_date,
            execution_time,
            checklist_path,
            internal_responsible,
            external_supplier,
            supplier_contact,
            service_order,
            status,
            certificate_path,
            observations,
            next_date,
            blocks_booking,
            notify_internal,
            notify_manager,
            notify_supplier,
            notify_users,
        ],
    )


def create_corrective_ticket(
    conn: sqlite3.Connection,
    *,
    equipment_id: int,
    reporter_id: int | None,
    title: str,
    description: str,
    occurrence_datetime: str,
    impact: str,
    priority: str,
    attachment_path: str | None,
    assigned_to: str | None,
    initial_diagnosis: str | None,
    probable_cause: str | None,
    operator_trained: str,
    external_supplier_needed: int,
    corrective_action: str | None,
    replaced_parts: str | None,
    costs: float | None,
    downtime_hours: float | None,
    conclusion_date: str | None,
    status: str,
    notify_technical: int,
    notify_manager: int,
    notify_supplier: int,
    notify_reporter: int,
) -> int:
    return insert_returning_id(
        conn,
        """
        INSERT INTO maintenance_corrective (
            equipment_id, reporter_id, title, description, occurrence_datetime, impact,
            priority, attachment_path, assigned_to, initial_diagnosis, probable_cause,
            operator_trained, external_supplier_needed, corrective_action, replaced_parts,
            costs, downtime_hours, conclusion_date, status, notify_technical,
            notify_manager, notify_supplier, notify_reporter
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            equipment_id,
            reporter_id,
            title,
            description,
            occurrence_datetime,
            impact,
            priority,
            attachment_path,
            assigned_to,
            initial_diagnosis,
            probable_cause,
            operator_trained,
            external_supplier_needed,
            corrective_action,
            replaced_parts,
            costs,
            downtime_hours,
            conclusion_date,
            status,
            notify_technical,
            notify_manager,
            notify_supplier,
            notify_reporter,
        ],
    )


def update_corrective_status(conn: sqlite3.Connection, ticket_id: int, status: str) -> None:
    conn.execute("UPDATE maintenance_corrective SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?", [status, ticket_id])
    conn.commit()


def create_supply(
    conn: sqlite3.Connection,
    *,
    supply_type: str | None,
    supply_name: str,
    supply_code: str | None,
    commercial_name: str | None,
    manufacturer: str | None,
    manufacturer_code: str | None,
    category: str | None,
    physical_state: str | None,
    application_function: str | None,
    addition_mode: str | None,
    compatible_model_family: str | None,
    unit: str,
    current_quantity: float,
    minimum_quantity: float,
    lot: str | None,
    expiration_date: str | None,
    location: str | None,
    responsible_name: str | None,
    safety_doc_path: str | None,
    technical_doc_path: str | None,
    density: float | None,
    recommended_concentration: str | None,
    recommended_temperature: str | None,
    characterization_summary: str | None,
    notes: str | None,
) -> int:
    supply_type = supply_type.strip() if supply_type and supply_type.strip() else "Insumo"
    return insert_returning_id(
        conn,
        """
        INSERT INTO supplies (
            supply_type, supply_name, supply_code, commercial_name, manufacturer,
            manufacturer_code, category, physical_state, application_function,
            addition_mode, compatible_model_family, unit, current_quantity, minimum_quantity,
            lot, expiration_date, location, responsible_name, safety_doc_path,
            technical_doc_path, density, recommended_concentration,
            recommended_temperature, characterization_summary, active, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
        """,
        [
            supply_type,
            supply_name,
            supply_code,
            commercial_name,
            manufacturer,
            manufacturer_code,
            category,
            physical_state,
            application_function,
            addition_mode,
            compatible_model_family,
            unit,
            current_quantity,
            minimum_quantity,
            lot,
            expiration_date,
            location,
            responsible_name,
            safety_doc_path,
            technical_doc_path,
            density,
            recommended_concentration,
            recommended_temperature,
            characterization_summary,
            notes,
        ],
    )


def update_supply(
    conn: sqlite3.Connection,
    supply_id: int,
    *,
    supply_type: str | None,
    supply_name: str,
    supply_code: str | None,
    commercial_name: str | None,
    manufacturer: str | None,
    manufacturer_code: str | None,
    category: str | None,
    physical_state: str | None,
    application_function: str | None,
    addition_mode: str | None,
    compatible_model_family: str | None,
    unit: str,
    minimum_quantity: float,
    lot: str | None,
    expiration_date: str | None,
    location: str | None,
    responsible_name: str | None,
    safety_doc_path: str | None,
    technical_doc_path: str | None,
    density: float | None,
    recommended_concentration: str | None,
    recommended_temperature: str | None,
    characterization_summary: str | None,
    active: int,
    notes: str | None,
) -> None:
    supply_type = supply_type.strip() if supply_type and supply_type.strip() else "Insumo"
    conn.execute(
        """
        UPDATE supplies
        SET supply_type = ?,
            supply_name = ?,
            supply_code = ?,
            commercial_name = ?,
            manufacturer = ?,
            manufacturer_code = ?,
            category = ?,
            physical_state = ?,
            application_function = ?,
            addition_mode = ?,
            compatible_model_family = ?,
            unit = ?,
            minimum_quantity = ?,
            lot = ?,
            expiration_date = ?,
            location = ?,
            responsible_name = ?,
            safety_doc_path = ?,
            technical_doc_path = ?,
            density = ?,
            recommended_concentration = ?,
            recommended_temperature = ?,
            characterization_summary = ?,
            active = ?,
            notes = ?,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        """,
        [
            supply_type,
            supply_name,
            supply_code,
            commercial_name,
            manufacturer,
            manufacturer_code,
            category,
            physical_state,
            application_function,
            addition_mode,
            compatible_model_family,
            unit,
            minimum_quantity,
            lot,
            expiration_date,
            location,
            responsible_name,
            safety_doc_path,
            technical_doc_path,
            density,
            recommended_concentration,
            recommended_temperature,
            characterization_summary,
            active,
            notes,
            supply_id,
        ],
    )
    conn.commit()


def create_supply_movement(
    conn: sqlite3.Connection,
    *,
    supply_id: int,
    movement_type: str,
    movement_date: str,
    quantity: float,
    user_id: int | None,
    project_id: int | None,
    purpose: str | None,
    document_path: str | None,
) -> tuple[bool, str, int | None]:
    row = conn.execute("SELECT * FROM supplies WHERE id = ?", [supply_id]).fetchone()
    if not row:
        return False, "Insumo não encontrado.", None
    if quantity <= 0:
        return False, "A quantidade precisa ser maior que zero.", None

    movement_type = movement_type.lower()
    current = float(row["current_quantity"] or 0)
    delta_map = {
        "entrada": quantity,
        "saída": -quantity,
        "saida": -quantity,
        "descarte": -quantity,
        "ajuste positivo": quantity,
        "ajuste negativo": -quantity,
    }
    if movement_type not in delta_map:
        return False, "Tipo de movimentação inválido.", None
    new_quantity = current + delta_map[movement_type]
    if new_quantity < -1e-9:
        return False, f"Saldo insuficiente. Saldo atual: {current:g} {row['unit'] or ''}.", None

    movement_id = _execute_insert_returning_id(
        conn,
        """
        INSERT INTO supply_movements (
            supply_id, movement_type, movement_date, quantity, unit,
            user_id, project_id, purpose, document_path
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            supply_id,
            movement_type,
            movement_date,
            quantity,
            row["unit"],
            user_id,
            project_id,
            purpose,
            document_path,
        ],
    )
    conn.execute(
        "UPDATE supplies SET current_quantity = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
        [new_quantity, supply_id],
    )
    conn.commit()
    return True, f"Movimentação registrada. Novo saldo: {new_quantity:g} {row['unit'] or ''}.", movement_id
