smtp_server = "smtp.gmail.com"
smtp_port = 587

sender_email = "labcim.manager@gmail.com"
sender_name = "LabCim Manager"

smtp_username = "labcim.manager@gmail.com"
smtp_password = "bftl yung jzin wmka"