[theme]
base = "light"
primaryColor = "#0033A0"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102A43"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[server]
enableStaticServing = true
baseUrlPath = "manager"
address = "127.0.0.1"
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
maxMessageSize = 50

[browser]
gatherUsageStats = false
